development:
  adapter: postgresql
  database: cellr
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cellr
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cellr
  pool: 5
  timeout: 5000
